### ISSUE TITLE
Localizing the Guide to different languages

### ISSUE THREAD

**Issue by xyx0826** [github/archive-program#1]
While open source software is written by people from all over the world, "it is not guaranteed that the inheritors of this archive will know English," as mentioned by the guide.

The guide also serves as a great introduction to programming and data storage. Through translation, we can make it more accessible not only to the Vault's future handlers, but also to the general public interested in computer principles.

## Volunteers
|Language|GitHub user|
|----------|------------|
|Bulgarian|@sahwar|
|German|@marcauberer|
|Romanian|@vladfrangu|
|Simplified Chinese|@xyx0826|
|Spanish|@erubio0|

**Comment by erubio0** [comment]
Here's a volunteer for a possible Spanish translation of this guide, or any other document of the project.

**Comment by vladfrangu** [comment]
I volunteer for a Romanian translation of this guide, or any other documents! 😄

**Comment by xyx0826** [comment]
@erubio0 @vladfrangu I can do Simplified Chinese. 🙂

Since GitHub embeds this guide at the beginning of each reel uncompressed, I doubt there's enough space for all the language versions. The best is to include all translated versions in this repo. Still waiting on an official reply but the least we can do is to create repos for localized versions so they'll be included in the archive.

We can also include a note in the master guide, e.g. "our open source community has translated this guide into different languages, and they're scattered in repos around the archive..."

**Comment by marcauberer** [comment]
I'd volunteer for the German translation ☝️

**Comment by marcauberer** [comment]
I started with the translation.
I'll open a pull request as soon as it's ready.

**Comment by sahwar** [comment]
I can help with translating the GUIDE.md into Bulgarian. If I can't complete the translation, other Bulgarian-language native users may finish my translation.

(the same message but in Bulgarian:)

Мога да помогна да се преведе на български GUIDE.md. Ако не мога да завърша превода, други ползватели на българския език като роден/първи език може да довършат превода ми.

**Comment by xyx0826** [comment]
Been a bit busy but I'm still working on this. Almost done :)

**Comment by marcauberer** [comment]
Me too. Half the way through!

**Comment by erubio0** [comment]
I'm working on it ;)

**Comment by marcauberer** [comment]
Hi,
I've stopped my work due to a shortage of time for the German translation. I created a pr to give you my current progress. Maybe we can find someone, who wants to finish the translation for me.

**Comment by schnittker** [comment]
I can finish your translation to German

**Comment by Jarvis-BITS** [comment]
I can contribute to Hindi translation!
Already changed some word and numbers from incorrect google translate to proper native tongue. Will sift through and see if there is anything else to change

**Comment by hemangandhi** [comment]
Hi! I can start working on a Japanese translation, but I'm not sure if I'm skilled enough to finish it well. I will have a PR for it and try asking around for corrections. (Same below in Japanese.)

今日は！日本語の翻訳始めたいと思いますけどうまくできませんかもしれない。PRを作りますと日本語を知っている知り合いの手伝い願います。（上は英語で同じことを書いています。）

**Comment by rezendi** [comment]
At present, we're limiting the translations of the Guide to professional translations. We may revisit this in future, but in the interim, closing this issue for now -
