### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by sivaraam** [github/archive-program#10]
A few possible improvements:

- [ ] Source code of open source software
    >  Open source software is made available to any and all who want to use it, at no cost, so they can in turn improve it, or use it to build something new and better.

    It might be better to explicitly mention that it is the source code that is made available to all, like so: *Source code of Open source software is made available to any and all ...*

- [ ] Open source software project
    > An open source software project

    Excuse me for the nitpick. We define this as *open source **software** project* and then refer to it as *open source project* in all other places. May be its better to just define it that way.

- [ ] GitHub not defined
  GitHub seems to be mentioned in a dozen places but I don't see any clear definition as to _what GitHub is_ in a way similar to how other things such as computer, Git etc. are defined. It would be nice to define it somewhere.

**Comment by rezendi** [comment]
The second one is an interesting nitpick, actually, since not all open source projects are software projects; will tweak the language for greater precision. The other two will be addressed as well.

**Comment by rezendi** [comment]
Addressed in PR #13.
