### ISSUE TITLE
Can I get "Arctic Code Vault Contributor" badge now after 2/2/2020?

### ISSUE THREAD

**Issue by YousifAbozid** [github/archive-program#109]
I didn't create a repo or make a commit in the last year, but few months age I start working on some projects, willI have Arctic Code Vault Contributor badge or I'm just missed the train?

**Comment by PalinuroSec** [comment]
as far as i know the code vault will be updated over time.
according to their FAQ (https://archiveprogram.github.com/faq/) they will evaluate if an update is necessary every 5 years

**Comment by YousifAbozid** [comment]
thanks @PalinuroSec for the info, I guess after five years maybe I can have this badge in the next update to the code vault, thanks a lot 💖
