### ISSUE TITLE
2D Barcode Format

### ISSUE THREAD

**Issue by anders94** [github/archive-program#118]
Is the code used to generate the frames available somewhere? Is that a standardized project?

cc @craSH

**Comment by rezendi** [comment]
It's available here, with a GPL license: https://github.com/piql/boxing

**Comment by craSH** [comment]
That seems to indicate it's the decoder only, which while definitely neat and useful (and thanks for linking to it), I wonder if the specific code used to generate the barcodes of the vault media is available? Similar to the question in https://github.com/github/archive-program/issues/45#issuecomment-720134658
