### ISSUE TITLE
Kinetophone Narration Software

### ISSUE THREAD

**Issue by goshu-poni** [github/archive-program#138]
I was wondering if my open source narration software, [Kinetophone](https://github.com/goshu-poni/kinetophone/blob/master/README.md) would be of use to this project.  It could potentially be adapted to generate images for use with your optical archiving system.  The soundtrack could be stored as [Optical Audio](https://en.wikipedia.org/wiki/Optical_sound#/media/File:35mm_film_audio_macro.jpg).

You could, for example, record a narration of your project to store in your archives as background and instructions.

The [Muybridge Horse](https://en.wikipedia.org/wiki/The_Horse_in_Motion) might also give you an idea of what I am describing.

**Comment by Glaferg** [comment]
No, this needs to be reopened and reconsidered.

**Comment by Glaferg** [comment]
We also need to consider vibration-based species reading this.
