### ISSUE TITLE
Binary size limit in bytes

### ISSUE THREAD

**Issue by joakim** [github/archive-program#14]
Does 100 KB denote 100 kB (100000 bytes) or 100 KiB (102400 bytes)?

According to [this Wikipedia article](https://en.wikipedia.org/wiki/Kilobyte), I would assume KiB.

**Comment by emijrp** [comment]
I assume 99,999 bytes just in case...

**Comment by joakim** [comment]
My file was 100002 bytes, which is why I asked :)

I managed to get it under 100000 bytes with `gzip -9` (max compression).

**Comment by emijrp** [comment]
I hope gzip is included...

**Comment by rezendi** [comment]
The answer is: 100KB denotes KiB. (And if it is 100 KiB exactly, it will be included.)

**Comment by joakim** [comment]
Thanks, that's good to know, even after the deadline :)
