### ISSUE TITLE
Technological terminology

### ISSUE THREAD

**Issue by Glaferg** [github/archive-program#144]
I read this and it is so wonderful but yet it relies on such complicated vernacular. We need to picture: How would you explain it to a toddler? What will we do if the concept of *mathematics* or *the internet* is lost? How can we write this with the least number of unique words? 

Also, has anyone used this to replace the text of the Simple English Wikipedia article on GitHub?

We should also use this material to teach children, so as to lint its complexity.

Good job though, this is masterful!

**Comment by TSNikkie** [comment]
Thx NikkieDickie
