### ISSUE TITLE
Wikis and other knowledge projects

### ISSUE THREAD

**Issue by emijrp** [github/archive-program#17]
Hello! I just read in your blog post[1] that you will add a snapshot of Wikipedia to the vault. It's great!

I created some time ago two repos when I learnt about the GitHub Vault, Wiktionary[2] and Wikispecies[3]. They include XML dumps of those wiki sites, only current versions for pages, and some metadata (date, username of last edit, etc).

Are you going to include in the wiki snapshot only Wikipedia? Only English? Full history or current versions only?

Other interesting projects which could be added, if there aren't issues (copyright or other), are: Project Gutenberg (60,000 books), Open Library (index of all known books) and Rosetta Project.

Thanks!

[1] https://github.blog/2020-02-03-the-arctic-code-vault-starts-production-and-your-open-source-projects-are-being-archived/
[2] https://github.com/emijrp/dictionaries-timecapsule
[3] https://github.com/emijrp/species-timecapsule

**Comment by rezendi** [comment]
These are great suggestions, thanks--

**Comment by rezendi** [comment]
Include in initial Tech Tree compilation.
