### ISSUE TITLE
Years and calendars

### ISSUE THREAD

**Issue by emijrp** [github/archive-program#19]
When we talk about year 2020 or other dates, we should clarify we use Gregorian calendar.[1]

[1] https://en.wikipedia.org/wiki/Gregorian_calendar

**Comment by joakim** [comment]
I think people 1000 years from know should understand that we used the Gregorian calendar in most of the world in 2020 AD/CE, and therefore any year number would by default reference the Gregorian calendar. Still, I agree that it should be clarified, as is the norm on Wikipedia and elsewhere. After all, [some countries](https://en.wikipedia.org/wiki/Adoption_of_the_Gregorian_calendar#Present_situation) have not adopted the Gregorian calendar and some use it alongside other calendars.

**Comment by rezendi** [comment]
Addressed in PR #26.
