### ISSUE TITLE
Insufficient Tech Tree explanation

### ISSUE THREAD

**Issue by racinmat** [github/archive-program#2]
In the guide, and also in the https://archiveprogram.github.com/faq/ tech tree is mentioned, but nowhere any example how it should look like, what should be its structure or any other guide for repo owners to make their tech tree. Is there any more info on this topic?

**Comment by rezendi** [comment]
The Tech Tree will occupy its own separate reel of the archive, and will include its own guide.

**Comment by mikew-lunarg** [comment]
Understood.  How/where/when will the content of the Tech Tree be available?   Eager to see the technical specifics!  Thanks

**Comment by souravjamwal77** [comment]
Please provide an explanation of how the GitHub tech tree is structured and how can we access it?

**Comment by cls-02** [comment]
Plot twist, there is none

**Comment by rezendi** [comment]
See new README...

**Comment by souravjamwal77** [comment]
What's the link for new README...

**Comment by nylki** [comment]
> What's the link for new README...
Its in the same location, but updated: https://github.com/github/archive-program/blob/master/README.md

**Comment by souravjamwal77** [comment]
@nylki Thanks, I will read this on weekend and I'm planning on making a Youtube video explaining how to decode a Github Arctic Reel. Let me know if you're interested.
