### ISSUE TITLE
QR code is inaccurate

### ISSUE THREAD

**Issue by oleliabo** [github/archive-program#23]
It is the 2D-barcode format "boxing" format that is used to code the digital data, see https://github.com/piql/boxing
Each pixel has 4 grey levels, storing 2 bits/pixel.

**Comment by marcauberer** [comment]
Otherwise we probably would have 400 film reels?!

**Comment by oleliabo** [comment]
> Otherwise we probably would have 400 film reels?!

yes, at least

**Comment by rezendi** [comment]
PiQL consistently refers to the data format as "QR codes" https://www.piql.com/future-proof-data-storage/ but this admittedly seems to be using the term more descriptively than prescriptively.

**Comment by oleliabo** [comment]
Yes QR code it used to explain the concept. Also note that the boxing format spec and decoder source code is stored on the reel to support future recovery.
