### ISSUE TITLE
Use plain text (.txt) file instead of markdown

### ISSUE THREAD

**Issue by prajapati-parth** [github/archive-program#3]
I think this guide should be a plain txt file that can be read and understood easily. GitHub would easily parse markdown to readable text. But what would happen when someone reaches the code vault in an age when there are no such parsers? 🤔

**Comment by xyx0826** [comment]
The guide is included at the beginning of every reel "in human-readable format" so I'd imagine it would appear on the film with style applied.

Other than that, Markdown is a very readable markup language, and the guide only makes use of title hashtags.

**Comment by prajapati-parth** [comment]
Right on! Closing this.
