### ISSUE TITLE
Programming Languages Summary - Choice of languages

### ISSUE THREAD

**Issue by peternewman** [github/archive-program#31]
I don't know where the choice of programming languages came from (or how it compares to the stats within the archive), but it seems to differ from those in the latest State of the Octoverse:
https://octoverse.github.com/#top-languages

Shell being the most obvious omission (and key to compiling quite a bit of software; see also Make etc).

**Comment by rezendi** [comment]
Thanks for the input. A greater panoply of languages will be addressed in the Tech Tree.
