### ISSUE TITLE
Delays?

### ISSUE THREAD

**Issue by emijrp** [github/archive-program#34]
Hello! Is this project suffering some delays due to coronavirus pandemic? Just curious. I hope everybody is fine. Thanks.

(Could repos with tag 'coronavirus', and related, be included after you started the snapshot?)

**Comment by rezendi** [comment]
Thanks for asking! Apologies for the delay in responding; we didn't want to give any imprecise predictions. There were a few logistical delays, but as recently announced, [they have been resolved](https://github.blog/2020-07-16-github-archive-program-the-journey-of-the-worlds-open-source-code-to-the-arctic/).
