### ISSUE TITLE
I have been forcibly selected without knowledge. (Hostage of the embodiment of stupidity wrapped into good)

### ISSUE THREAD

**Issue by moe123** [github/archive-program#36]
Please remove myself and any code I wrote* or  committed under, from your insanity project of polluting Arctic with insignificant  knowledge. You don't have my permission nor my blessing. I don't want my name or my production to be associated with you, that's a fondamental right.

* I have contribs in many open source projects over the past 3 decades, sure, beyond this avatar. You'll figure it out which ones yourself  (in my recollection under more than 15 different identities).

Idiocraty and arrogance at best.

Erratum
Forgot to conclude on a personal note: fuck off dimwits.

**Comment by ApolloZhu** [comment]
While waiting for GitHub to reply, you might want to checkout the [GitHub Archive Program FAQ](https://archiveprogram.github.com/faq/) or [contact GitHub support](https://support.github.com/).

> ## What if I want to opt out?
> 
> GitHub will archive only public repositories, so opting out is as simple as making your repository private. Alternatively, go to your repository’s Settings tab, scroll down to the “Data Services” section, and unselect the Preserve this repository checkbox. ***Please visit https://support.github.com/ for all other opt out concerns.***

> ## If I delete my repositories from GitHub, will it eventually be deleted from all warm storage partners?
> 
> Keeping a historic view is an important part of each archive. If you have a concern about your repository continuing to be a part of the archive, please contact the archives. ***For the GitHub Arctic Code Vault, we are unable to remove data that has already been stored.***

**Comment by moe123** [comment]
@ApolloZhu  certainly not. It does not interest me at all.

**Comment by jason-bowen-zheng** [comment]
You are so lucky(some of my Github repository have been choosen, too. But I'm just 15)! It's a good thing for future generations, isn't it. Why reject it? I don't think I have any regrets in my life. It was a very good experience.

In the end, we were all very lucky.
> Some translations may not be correct

**Comment by moe123** [comment]
@jason-bowen-zheng when I stated the word dimwit; this is factual; I won't expect any enlightenment  or intellectual fitness; so I am well aware, we don't expect much from your capacity to reason.

**Comment by smashah** [comment]
@moe123 PRs welcome

**Comment by jakejarvis** [comment]
I'll agree with you on one thing, this issue is indeed "idiocraty (????) and arrogance at best."

**Comment by moe123** [comment]
@jakejarvis  good for you.

**Comment by moe123** [comment]
@smashah  I PR code; the main purpose of this website; I am sorry this is not a PR but an issue and a legit request; it's already enough  painful  to be forced to intervene  for normality to be restored; I did not sign for or/and endorse this, neither I am a contributor and wish to have any involvement; that's part of your term of conditions; if you want to do so you do it with your own intellectual property not mine. Thank you.

**Comment by jakejarvis** [comment]
> It doesn't not cover any of this nor implicitly endorsing it.

It does, though:

https://docs.github.com/en/github/site-policy/github-terms-of-service#4-license-grant-to-us

Why do you still have an account (or 15 of them, no less) here then? That alone is giving consent...15 times.

Whether you personally agree with GitHub's activities or not, at the end of the day there are _plenty_ of other services without what is essentially a backup in Norway, and you **do** have the right to move your code elsewhere. I'd be willing to suggest a few if you'd like. 😊

**Comment by moe123** [comment]
@jakejarvis you are a ridiculous clown; keep it that way if you are happy with it we don't care much; however please go make your pity tours elsewhere.

**Comment by smashah** [comment]
@moe123 can you fill an issue template, please? I'll have the QA team look into it and we'll get back to you ASAP. Closing, thanks.

**Comment by jakejarvis** [comment]
@moe123 No need to get personal. Sounds like you're declining my offer for suggestions that fit your needs, so take care friend. :)

**Comment by marcauberer** [comment]
@moe123 I would recommend you to stay polite and objective. Otherwise, nobody will take you serious.

**Comment by moe123** [comment]
@smashah I already answer to you. I don't QA stupidity.

**Comment by smashah** [comment]
@moe123 Apologies for the misunderstanding; The QA team would QA this stupidity. Thanks

**Comment by moe123** [comment]
@jakejarvis  there is nothing personal; I already addressed one of your kind about the same somehow cognitive dysfonctionnement, it does not interest me-self same for your other partner: @marcauberer; keep your suggestion for your club.

@smashah I don't care much.

**Comment by marcauberer** [comment]
Nothing more to say. Request for locking this issue ...

**Comment by smashah** [comment]
Sorry @moe123 but the maintainers of this repo are mere Padawan volunteers. Repo admin have not given any contributors access to The Force™© so not sure how you this happened - I suggest bringing this up with the Jedi.

CC: @obiwankenobi

We'll get to the bottom of this. Thanks again.

**Comment by moe123** [comment]
@smashah  please, keep your second-hands references to low grade post-modern sci-fi productions. We have no interest in such sub-cultures if we can even label that "culture", neither we had or will. You can keep it simple by using plain words, thank you.

**Comment by smashah** [comment]
@moe123 Great, thanks for the heads up. The joke worked well at compile-time, maybe environment issue? Probably best to Dockerize it for the future.  I see your hint at the end, all future references will be using the Inception framework 👍

**Comment by tmegow** [comment]
@moe123 I'm stealing your code!

**Comment by jason-bowen-zheng** [comment]
1. I hope to close the issues soon, It will get out of control. Especially @moe123 .
2. Everyone has a different point of view. I think it helps, but you don't think so. __No problem!__
2.1 But you even scold other people's opinions(More than once). We have nothing to say. This is the moral issue. *Bye, Bye*.
3. You choose Github, you choose open source. So anyone can modify your code without asking for your opinion. Everyone's changes to your code are in line with the agreement.
4. The Github Archive Program is a great and forward-looking plan. Whether we are chosen or not, we should  support it. Instead of saying something like `Polluting Arctic with insignificant knowledge`
4.1 But I think you question the program. __No problem!__ Don't open an issues(发表一些不太好的话语like:`f*ck off dimwits`). You should go to the official and give your opinion on the program.

__Finally: *Bye, Bye*. I don't want to see you any more!__
> 没有道德的人在世界上还有很多, @moe123就是一个很好的例子.

**Comment by moe123** [comment]
@jason-bowen-zheng The Github Archive Program is a great and forward-looking plan, no, and no I don't support it, I despise it. You do whatever you want: quoting myself :  `scientism is a caricature of knowledge and mainly a psychical disease and disorder`; you have deformed mindset, good for you, we don't. Finally your ridiculous about my morality says a lot, when you have ethics; let us smile; 纸老虎.

**Comment by rezendi** [comment]
While we invite thoughtful skepticism of the program, this has degenerated into ad hominem attacks; closing accordingly.

**Comment by moe123** [comment]
@rezendi  weak minds always find sorry solutions; there is no ad hominem attacks; just answers; each of them adapted to level it started; I must say most intervenants do not shine by their brightness; they preach their cult. Please address my formal request; and I stand by the fuck off dimwits spelled with a u and not a blazing star. Quoting myself ``` I despise the policy of faits accomplis like anyone normally fit should.``` This is the embodiment of vulgarity and arrogance; those are not skepticism at all; just facts; now discussion can opinionated nobody ever died from such; meanwhile we don't voice an opinion; I don't know what you try to achieve here.

Thank you.

**Comment by smashah** [comment]
DW all, @moe123 is just a what happens when you run GPT-3 through a tin foil regression. Thanks for participating.

**Comment by moe123** [comment]
@smashah  you should wear it; it fits you.

**Comment by smashah** [comment]
Wow GPT-3 really is the future

A thread...

**Comment by moe123** [comment]
I am very human; I could even kick your butt live with no shame; at least if you want any-non-virtual check; it's gonna hurt for real.
