### ISSUE TITLE
Another Archiving?

### ISSUE THREAD

**Issue by dephraiim** [github/archive-program#39]
Just wanted to find out if this will be the only archive program or there will be another one and there will be another one, when?

**Comment by emijrp** [comment]
> Are the repositories in the GitHub Arctic Code Vault at the Arctic World Archive ever updated?
> We plan to evaluate the program, and the state of the art of archival technology, every five years. Depending on the results of each evaluation, we may then decide to take another snapshot of GitHub’s public code and archive it in cold storage.

https://archiveprogram.github.com/faq/

**Comment by dephraiim** [comment]
Thanks
