### ISSUE TITLE
Concepts of time

### ISSUE THREAD

**Issue by brianteeman** [github/archive-program#4]
In many places in this document phrases are used which relate to time or the passage of time. These concepts are artificial constructs that may be meaningless in the future.

For example (emphasis mine)

> Most **_modern_** languages include libraries of pre-written functions, and such libraries can be very voluminous and elaborate. Some of **_today's_** most popular programming languages include:

> C, one of the **_oldest_** and fastest

**Comment by sivaraam** [comment]
Here's one more:

> *You may be reading this one year from **now**, ...*

**Comment by rezendi** [comment]
I'm a little baffled by this one. If its inheritors are capable of interpreting the archive at all, they'll be able to interpret "today" as being "the time at which the archive was created," etc., in the same way that we read Gibbon's DECLINE AND FALL OF THE ROMAN EMPIRE without any difficulty understanding that his frequent uses of the word "modern" refer to the era when he wrote that history, not to the current era or to the Roman one.

**Comment by sivaraam** [comment]
Of course, there's a possibility that the inheritors could interpret it properly. I think there's better if we are a bit more clear when we can. For example, 

> You may be reading this one year from now, ...

This could be replaced with *You may be reading this one year from **the time of writing**, ...*.

> Some of today's most popular programming languages include:

This could be replaced with *Some of the most popular programming languages during the period of writing include:*

Just a few suggestions 🙂

**Comment by rezendi** [comment]
In the absence of a deluge of disagreement, I'm going to close this one as WONTFIX.

**Comment by brianteeman** [comment]
That's very disappointing to hear. Why did you bother to even open this for comment
