### ISSUE TITLE
[Suggestion] Publish the tech tree

### ISSUE THREAD

**Issue by Malfrador** [github/archive-program#41]
It would be nice to publish the tech tree reel at some point, if possible in any way. It obviously is too late now to change anything on it, but it surely is still an interesting resource.

**Comment by rezendi** [comment]
It's actually not too late, as the tech tree is being added subsequent to the code itself, and per our latest [blog post](https://github.blog/2020-07-16-github-archive-program-the-journey-of-the-worlds-open-source-code-to-the-arctic/):

> We will soon publish to the Archive Program’s GitHub repository a very initial draft list of works selected for the Tech Tree, along with, importantly, a request for community input. We look forward to incorporating ideas and suggestions from the GitHub community before the Tech Tree is added to the Arctic Code Vault.

So watch this repo for that soon --

**Comment by rezendi** [comment]
See new README...
