### ISSUE TITLE
Request for disclaimer about private/sensitive info

### ISSUE THREAD

**Issue by AB1908** [github/archive-program#49]
This is a great project and I can understand its significance. However, I would like to point out that several people may (unknowingly) have private and/or sensitive info recorded in their repositories which may be archived. While this information is likely publicly accessible and may have been scraped by others, it would still serve a user well to be able to delete said info when they so choose. Now that this information may be archived, users may suddenly want to double check and/or opt-out. 

Of course, [GitHub's Privacy Policy](https://docs.github.com/en/github/site-policy/github-privacy-statement#what-information-github-does-not-collect) clearly notes that:

> If you choose to store any Sensitive Personal Information on our servers, you are responsible for complying with any regulatory controls regarding that data.

but it is very likely that people have not read the Privacy Policy and it would thus be helpful to add a small disclaimer that sensitive information may be present in a user's repository and they may want to review it. Again, I understand that this is the user's responsibility and they _should_ have dealt with it in the first place, but a small nudge in the right direction would be immensely helpful.

**Comment by yzjing** [comment]
I second this -- an opt-out option will be great for many users.

**Comment by AB1908** [comment]
An opt-out exists in the repository settings. My wish is that it is made more prominent.

**Comment by rezendi** [comment]
As mentioned, an opt-out exists; we appreciate the input that more prominence for it might be desirable.
