### ISSUE TITLE
Neutral language not opinionated

### ISSUE THREAD

**Issue by brianteeman** [github/archive-program#5]
The tone should be descriptive and not opinionated. Other than exposing the personal views of the anonymous authors statements such as the following should play no part.

Examples (emphasis mine)

>  a **_clumsy_** but straightforward language

> a very **_cryptic, limited,_** but fast and powerful family

**Comment by rezendi** [comment]
On the other hand, we do want the guide to be descriptive. I'm not aware of anyone who disputes that raw assembler is a cryptic and limited tool?

**Comment by brianteeman** [comment]
There will certainly be a lot of php developers who would not appreciate it being called clumsy

**Comment by rezendi** [comment]
That's fair. I'll try to come up with a wording for PHP which is descriptive without being pejorative.

**Comment by rezendi** [comment]
Addressed in PR #26.
