### ISSUE TITLE
Factual error

### ISSUE THREAD

**Issue by brianteeman** [github/archive-program#6]
This is a factual statement which is incorrect
> This is known as the closed source model, and, historically, was the early, crude approach to software development.

Code was all open before it was later closed and then often open again.

Source https://en.wikipedia.org/wiki/History_of_free_and_open-source_software
> In the 1950s and 1960s, computer operating software and compilers were delivered as a part of hardware purchases without separate fees. At the time, source code, the human-readable form of software, was generally distributed with the software providing the ability to fix bugs or add new functions.[1] Universities were early adopters of computing technology. Many of the modifications developed by universities were openly shared, in keeping with the academic principles of sharing knowledge, and organizations sprung up to facilitate sharing.

**Comment by rezendi** [comment]
That's a fair point; we'll clarify accordingly.

**Comment by rezendi** [comment]
Addressed in PR #13.
