### ISSUE TITLE
In which reel are our repos?

### ISSUE THREAD

**Issue by emijrp** [github/archive-program#62]
Is there a way to know where in the reels is a repo? Something like a map or index.

**Comment by emijrp** [comment]
> As the Tech Tree is a companion piece to the GitHub Arctic Code Vault, it will contain an index with the name, brief description, and film reel number for all of the GitHub repositories stored in the Arctic Code Vault, i.e. every active public GitHub repo as of 02/02/2020.

**Comment by edsu** [comment]
Does anyone know where the Tech Tree work is happening?

**Comment by edsu** [comment]
Oh, [right here](https://github.com/github/archive-program/blob/master/TheTechTree.md)!
