### ISSUE TITLE
Futurism books

### ISSUE THREAD

**Issue by emijrp** [github/archive-program#67]
I can't see in the Tech Tree any book regarding futurism, technological singularity, predictions, etc.[1]

[1] https://en.wikipedia.org/wiki/Ray_Kurzweil

**Comment by rezendi** [comment]
The expectation is that the inheritors will not especially require our predictions of the future in which they live :) but that said we're open to PRs nominating new material --

**Comment by rezendi** [comment]
On further consideration I just fundamentally don't think this is essential cultural context. It will all be described by Wikipedia, which is included.
