### ISSUE TITLE
Separate "Fundamentals of computing" and "Internet"

### ISSUE THREAD

**Issue by nferraz** [github/archive-program#69]
The books about "Internet" should be moved to "Networking and connectivity":

### Fundamentals of computing

- The Pattern On The Stone by W. Daniel Hills (Basic Books)
- But How Do It Know? by J. Clark Scott (John C Scott)
- Code: The Hidden Language of Computer Hardware and Software by Charles Petzold (Pearson Education)
- The Elements of Computing Systems: Building a Modern Computer from First Principles by Noam Nisan (MIT Press)

### Networking and Internet

- Cabling: The Complete Guide To Copper and Fiber-Optic Networking by Andrew Oliviero and Bill Woodward (Wiley)
- Ethernet: The Definitive Guide by Charles E. Spurgeon and Joann Zimmerman (O'Reilly)
- Understanding TCP/IP by Alena Kabelová and Libor Dostálek (Packt)
- (...)
- Tubes: A Journey To The Center Of The Internet by Andrew Blum (HarperCollins)
- Introduction to Networking: How the Internet Works by Charles Severance, illustrated by Mauro Toselli and Aimee Andrion (Charles Severance)

**Comment by rezendi** [comment]
I think this is more an aesthetic issue than anything else.
