### ISSUE TITLE
Replace implementation-specific titles

### ISSUE THREAD

**Issue by nferraz** [github/archive-program#70]
Replace the following titles:

- Learning MySQL and MariaDB by Russell J. T. Dyer (O'Reilly)
- PostgreSQL Development Essentials by Manpreet Kaur, Baji Shaik (Packt)

With a single title about data modeling and database design:

- Database Design for Mere Mortals: A Hands-On Guide to Relational Database Design, Michael J. Hernandez (Addison-Wesley Professional)

**Comment by jodyswartz** [comment]
I've removed a  the 2 books  & replaced it with a single book. As, well as I have added a book in the modern  software development section in my pull request.

**Comment by rezendi** [comment]
Done - thanks!
