### ISSUE TITLE
Replace Javascript titles

### ISSUE THREAD

**Issue by nferraz** [github/archive-program#72]
Instead of:

- Learning JavaScript by Ethan Brown (O'Reilly)
- Mastering JavaScript Functional Programming by Federico Kereki (Packt)

I recommend the following books:

- JavaScript: The Definitive Guide by David Flanagan (O'Reilly)
- JavaScript: The Good Parts by Douglas Crockford (O'Reilly)

**Comment by rezendi** [comment]
Thanks for this; will look into it.

**Comment by nferraz** [comment]
As I wrote on ticket #73, we may not need books about Javascript.

All we really need is Assembly and C.

- Assembly, to make the first C compiler; 
- C, to build everything else: Linux, Javascript, Python, Java, LISP, etc.

We can learn Javascript and all the other programming languages from the source code, documentation, tests and other projects.

For example, we could compare different implementations of [mal](https://github.com/kanaka/mal) to learn how C, Python, Java, Javascript, LISP and many other languages implement the same project. A kind of rosetta stone of programming languages!

**Comment by rezendi** [comment]
Done.
