### ISSUE TITLE
Programming languages

### ISSUE THREAD

**Issue by nferraz** [github/archive-program#73]
The current list of programming languages is quite... arbitrary. 

I suggest the following languages based on their historical importance and current popularity:

1) Python
2) Java
3) Javascript
4) C
5) LISP (*)

(*) "Lisp is worth learning for the profound enlightenment experience you will have when you finally get it; that experience will make you a better programmer for the rest of your days, even if you never actually use Lisp itself a lot." (Eric S. Raymond)

Other languages that could be mentioned:

6) C#
7) Swift
8) Kotlin
9) Go
10) Rust
11) Scala
12) Lua
13) Perl
14) Julia
15) Haskell

**Comment by aviboy2006** [comment]
Shall i pick this ?

**Comment by rezendi** [comment]
Thanks for this; will look into it. We are also open to PRs adding new material for new languages --

**Comment by nferraz** [comment]
If your goal is to have a comprehensive library, you could add hundreds of different titles.

But, if your goal is to provide *enough* information to bootstrap society, the list could be as simples as:

1. Assembly
2. C

Assembly is necessary to build the first C compiler.

The C compiler is necessary to build the next generation of tools -- including the entire GNU/Linux, gcc, python, node, many flavors of lisp, etc.

You don't have to include any other books because the languages themselves are available on github. For instance:

- Python: [cpython](https://github.com/python)
- Javascript: [NodeJS](https://github.com/nodejs)
- Java: [OpenJDK](https://github.com/openjdk)
-  C: [llvm](https://github.com/llvm)
- LISP: [chicken](https://github.com/alaricsp/chicken-scheme), [racket](https://github.com/racket/) or [mal](https://github.com/kanaka/mal)

The last one, [mal](https://github.com/kanaka/mal), is like a rosetta stone of programming languages: it shows how to implement itself in different programming languages.

With that being said, this my short list of programming books to bootstrap civilization:

0. Microprocessor data sheets (for instance, the 8086 data sheet by Intel Corporation) 
1. [Programming from the Ground Up](http://savannah.nongnu.org/projects/pgubook/) by Jonathan Bartlett (GNU Free Documentation License)
2. The C Programming Language by K&R

That's all!

**Comment by schierlm** [comment]
IBTD.

> Assembly is necessary to build the first C compiler.

I doubt that most C compilers were actually built in assembly. Probably some "intermediate level" language like COBOL or Forth has been used.

> The C compiler is necessary to build the next generation of tools -- including the entire GNU/Linux, gcc, python, node, many flavors of lisp, etc.


Unfortunately, just a C compiler is no longer sufficient to bootstrap recent versions of most modern languages. For example, the GNU compiler collection (at least version 4 and newer) does not bootstrap compile with just a C compiler, you'd need a C++ compiler for most languages and an Ada compiler for Ada. OpenJDK 8 needs an OpenJDK 7 compiler to bootstrap. When older versions are available, you could use those (e.g. start with gcc 2.95 which can be compiled with most simple C compilers, or start with gcj to build OpenJDK7 to build OpenJDK8), but older versions are not included in the Arctic Code Vault.

On the other hand, not every bootstrap path starts with Assembly and C. mescc, albeit written in Scheme., is a C compiler that is powerful enough to compile other C compilers.

Also, I do not believe that the best way to understand design decisions of a programming language (or to learn using it) is looking at its compiler source code (probably written in the language itself) or trying to get it compiled and running. 

So, the decision which language books to include should not be focused on which languages we used to bootstrap other languages, but rather which languages include interesting concepts which may be of use for new languages made by the future civilization, or which languages comprise most of the archive's contents.


Trying to bootstrap our current ecosystem of programming language compilers from just the Arctic Code Vault (assuming there is no other knowlege about computers left) will be tricky in any case, so probably the civilization will either do their own compilers/interpreters for the languages that are useful or port the software to other languages available.

**Comment by nferraz** [comment]
> I doubt that most C compilers were actually built in assembly. Probably some "intermediate level" language like COBOL or Forth has been used.

Good point!

I would expand my list of books to:

0. Microprocessor data sheets (for instance, the 8086 data sheet by Intel Corporation)
1. Assembly
2. Forth (see [jonesforth](https://github.com/nornagon/jonesforth), written in assembly)
3. C/C++

> Unfortunately, just a C compiler is no longer sufficient to bootstrap recent versions of most modern languages.

I agree.

But that doesn't mean you need *books* to write your second, third and next generation of tools.

Books about compilers and interpreters would be far much more useful than books about specific technologies.

* Lex & Yacc by John R. Levine, Tony Mason, Doug Brown (O'Reilly)
* Compilers: Principles, Techniques, and Tools by Alfred V. Aho, Ravi Sethi, Jeffrey D. Ullman (Addison-Wesley)
* Modern Compiler Implementation in C by Andrew W. Appel, Maia Ginsburg (Cambridge University Press)
* Structure and Interpretation of Computer Programs, by Abelson, Sussman, and Sussman (MIT Press)

> On the other hand, not every bootstrap path starts with Assembly and C. mescc, albeit written in Scheme., is a C compiler that is powerful enough to compile other C compilers.

I agree - but how do you bootstrap your first Scheme compiler?

> So, the decision which language books to include should not be focused on which languages we used to
> bootstrap other languages, but rather which languages include interesting concepts which may be of use
> for new languages made by the future civilization, or which languages comprise most of the archive's
> contents.

In that case, we could probably expand the list to:

0. Microprocessor data sheets (for instance, the 8086 data sheet by Intel Corporation)
1. Assembly
2. Forth (see [jonesforth](https://github.com/nornagon/jonesforth), written in assembly)
3. C/C++
4. Python
5. Javascript
6. Java

And so on.

According to [The State of the Octoverse](https://octoverse.github.com/#top-languages), developers collaborated in more than 370 primary languages on GitHub.

I recommend that we stop right before PHP. :)

**Comment by rezendi** [comment]
This is an interesting conversation but seems superseded now.
