### ISSUE TITLE
End frame inconsistency

### ISSUE THREAD

**Issue by Harmon758** [github/archive-program#8]
> So, using the hypothetical CPython example, the item in this list with the ID 12345 might have a start frame of 054321, a start byte of 03210321, an end frame of of 054545, and an end byte of 12321232.

This specifies the end frame as 54545, but in the next paragraph:

>  Decode all frames from the start frame, 54321, to the end frame, 54544

54544 is referred to as the end frame.

Is this because the value given for the end frame is exclusive and is actually the value for the frame after the last frame in the range? or is this just a mistake in the guide?

If it's the former, an explanation in the guide to clarify the inconsistency might be necessary.

**Comment by rezendi** [comment]
Will address, thanks--

**Comment by rezendi** [comment]
Addressed in PR #13.
