### ISSUE TITLE
Separate Compilers, assembler, and operating systems

### ISSUE THREAD

**Issue by nferraz** [github/archive-program#87]
Compilers, assembler, and operating systems are three different topics.

Assembly should be part of **Programming languages** (see #73).

The other should be split in two topics:

### Compilers and Interpreters

* Lex & Yacc by John R. Levine, Tony Mason, Doug Brown (O'Reilly)
* Compilers: Principles, Techniques, and Tools by Alfred V. Aho, Ravi Sethi, Jeffrey D. Ullman (Addison-Wesley)
* Modern Compiler Implementation in C by Andrew W. Appel, Maia Ginsburg (Cambridge University Press)
* Structure and Interpretation of Computer Programs, by Abelson, Sussman, and Sussman (MIT Press)

### Operating Systems

* Modern Operating Systems by Andrew S. Tanenbaum (Pearson PLC)
* Operating Systems: Design and Implementation by Andrew S. Tanenbaum (Prentice Hall)

And maybe:

* The Art of Unix Programming by Eric S. Raymond (Addison-Wesley, but also available under a Creative Commons license)

**Comment by rezendi** [comment]
We're fairly comfortable with the current structure.
