### ISSUE TITLE
Guidelines

### ISSUE THREAD

**Issue by nferraz** [github/archive-program#88]
Here are some ideas/guidelines to evaluate books about technology (but **not** literature):

1. **General principles** instead of **specific technologies**
   * Example: "Relational Databases" instead of  "MySQL" or "PostgreSQL"
   * Exceptions: technologies that became standards with multiple implementations: C, UNIX, etc.

2. **Technical** instead of **pop science**
   * Example: "The Elements of Computing Systems" instead of "But How Do It Know?" (which I assume is intended for a general audience)

3. **Comprehensive** instead of **partial**
   * Example: "The Art of Computer Programming" instead of "Everyday Data Structures"

4. **Unique** instead of **redundant**
   * We don't need several books about each topic.
   * If you have to pick one, pick the most general, technical and comprehensive :)

5. Optional, but recommended: include **official standards** when possible

   * Examples:
      * [W3 standards](https://www.w3.org/standards/) (HTTP, HTML, XML, CSS, etc) 
      * [ECMAScript](https://www.ecma-international.org/publications/standards/Ecma-262.htm) (a.k.a. "Javascript")
      * [C18](https://www.iso.org/standard/74528.html)
      * [Scheme R6RS](http://www.r6rs.org/)
      * [Java Virtual Machine](https://docs.oracle.com/javase/specs/jvms/se14/html/)
      * etc.

   * Note: We should still include *books* about each one of these topics; but the standards can be used as reference.

---

I also propose the following changes in the structure:

1. Split "Fundamentals of computing" and "the Internet":
   * "Fundamentals of computing"
   * Move "the internet" to "Networking"
2. Split "Compilers, Assembler and Operating systems":
   * "Compilers and Interpreters"
   * "Operating Systems"
   * Move "Assembler" to "Programming Languages".

---

With that in mind, here's a shorter list of books for sections 1 to 7:

### 1. Fundamentals of computing

* Code: The Hidden Language of Computer Hardware and Software by Charles Petzold (Pearson Education)
* The Elements of Computing Systems: Building a Modern Computer from First Principles by Noam Nisan (MIT Press)

### 2. Algorithms and data structures

* The Art of Computer Programming by Donald Knuth (Pearson)

Optional:

* Introduction to Algorithms, by Thomas H. Cormen (MIT Press)

### 3. Compilers and Interpreters

* Compilers: Principles, Techniques, and Tools by Alfred V. Aho, Ravi Sethi, Jeffrey D. Ullman (Addison-Wesley)
* Modern Compiler Implementation in C by Andrew W. Appel, Maia Ginsburg (Cambridge University Press)
* Structure and Interpretation of Computer Programs, by Abelson, Sussman, and Sussman (MIT Press)

Optional:

* Lex & Yacc by John R. Levine, Tony Mason, Doug Brown (O'Reilly)

### 4. Programming Languages

* Assembly: Programming from the Ground Up by Jonathan Bartlett (GNU Free Documentation License)
* Forth: A sometimes minimal FORTH compiler and tutorial for Linux / i386 systems, by Richard W.M. Jones (PUBLIC DOMAIN) 
* C: C Programming Language, by K&R (Pearson)
* C++: C++ Programming Language, by Bjarne Stroustrup (Pearson)
* Scheme: How to Design Programs, by Matthias Felleisen (MIT Press, Creative Commons CC BY-NC-ND)

Optional:

* Javascript: JavaScript: The Definitive Guide, by David Flanagan (O'Reilly)
* Python: ?
* Java: ?

### 5. Operating systems

* Modern Operating Systems by Andrew S. Tanenbaum (Pearson PLC)
* Operating Systems: Design and Implementation by Andrew S. Tanenbaum (Prentice Hall)
* Operating System Concepts, by Abraham Silberschatz (Willey)
* Advanced Programming in the UNIX Environment, by W. Richard Stevens (Addison-Wesley Professional)
* The Art of Unix Programming by Eric S. Raymond (Addison-Wesley, but also available under a Creative Commons license)

Optional:

* The Linux Programming Interface, by Michael Kerrisk (No Starch Press)

### 6. Databases

* A Relational Model of Data for Large Shared Data Banks, by E.F.Codd (IBM Research Laboratory) 
* An Introduction to Database Systems, by C.J. Date (Pearson)
* Fundamentals of Database Systems, by Ramez Elmasri (Pearson)

### 7. Networking

* Cabling: The Complete Guide To Copper and Fiber-Optic Networking by Andrew Oliviero and Bill Woodward (Wiley)
* Ethernet: The Definitive Guide by Charles E. Spurgeon and Joann Zimmerman (O'Reilly)
* TCP/IP Illustrated (volumes 1-3), by Richard Stevens (Addison-Wesley Professional)
* DNS and BIND by Cricket Liu and Paul Albitz (O'Reilly)
* HTTP: The Definitive Guide by David Gourley, Brian Totty, Marjorie Sayer, Anshu Aggarwal, and Sailu Reddy (O'Reilly)
* Computer Networks, by Andrew S. Tanenbaum (Pearson)

---

Before adding a book, ask yourself: is book about general principles? Is it technical? Is it comprehensive? Does it provide unique information?

**Comment by rezendi** [comment]
Thanks for this. I think fundamentally we'll keep the structure and general granularity level we have now, but will incorporate some of these.
